name: "CI-CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Zip dist folder
        if: github.event_name != 'pull_request'
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Upload build artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist.zip

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment: n8n

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - name: Deploy to n8n via cURL
        run: |
          set -e

          echo "Deploying dist.zip to n8n at $DEPLOY_URL..."
          response=$(curl -s -o response.log -w "%{http_code}" \
            -X POST "${{ vars.DEPLOY_URL }}" \
            -H "Authorization: Bearer ${{ secrets.N8N_TOKEN }}" \
            -F "file=@dist.zip")

          if [[ "$response" -ne 200 ]]; then
            echo "❌ Deployment failed with HTTP $response"
            echo "Response body:"
            cat response.log
            exit 1
          else
            echo "✅ Deployment succeeded."
          fi
